### PR TITLE
Add complete Aaron Graham collection

### PR DESCRIPTION
**Pull request by sebamarynissen**
This adds metadata for [all of Aaron Graham's BATs](https://community.simtropolis.com/profile/226625-aaron-graham/content/?type=downloads_file), except for a few early ones that have been left out intentionally.

It looks like cicdec is extracting everything nicely, except for 1 package: the Maxis nite version of [41 Park Avenue](https://community.simtropolis.com/files/file/27913-nybt-41-park-avenue/) fails to extract properly. @memo33 could you check if this happens with you on Linux as well? If I run cicdec manually on the installer, it gives me the following error:

```
cicdec -v 40 "Install NYBT 41 Park Avenue (Maxis Nite).exe"
cicdec - A Clickteam Install Creator unpacker by Bioruebe (https://bioruebe.com), 2019-2021, Version 3.0.1, Released under a BSD 3-Clause style license

Extracts files from installers made with Clickteam Install Creator

Usage: cicdec [<options>...] <installer> [<output_directory>]

<options>:
  -v <version>  Extract as installer version <version>. Auto-detection might not always work correctly, so it is possible to explicitly set the installer version.

  -db   Dump blocks. Save additional installer data like registry changes, license files and the uninstaller. This is considered raw data and might not be readable or usable.

  -dfb  Dump file block. This is raw binary data containing all files in compressed form and only useful for debugging purposes.

  -si   Simulate extraction without writing files to disk.

---------------------------------------------------------------------
Starting extraction at offset 139270

Reading block 0x1435 UNKNOWN_FONT     with size 617
Reading block 0x1436 UNKNOWN_DATA     with size 107329
Reading block 0x143E STRINGS          with size 1651
Reading block 0x1445 REGISTRY_CHANGES with size 128
Reading block 0x143A FILE_LIST        with size 538
Reading block 0x7F7F FILE_DATA        with size 4986159
Reading block 0x152F 5423             with size 1750745602

11 files in installer


Starting extraction as installer version 40

1/11    4Model


The file C:\Users\sebam\Documents\SimCity 4\sc4pac\cicdec\Install NYBT 41 Park Avenue (Maxis Nite)\4Model already exists. Overwrite? [y]es | [N]o | [r]ename | [a]lways | n[e]ver | rename a[l]l
y
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
2/11    4Model


The file C:\Users\sebam\Documents\SimCity 4\sc4pac\cicdec\Install NYBT 41 Park Avenue (Maxis Nite)\4Model already exists. Overwrite? [y]es | [N]o | [r]ename | [a]lways | n[e]ver | rename a[l]l
y
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
3/11    4Model


The file C:\Users\sebam\Documents\SimCity 4\sc4pac\cicdec\Install NYBT 41 Park Avenue (Maxis Nite)\4Model already exists. Overwrite? [y]es | [N]o | [r]ename | [a]lways | n[e]ver | rename a[l]l
y
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
4/11    4Model


The file C:\Users\sebam\Documents\SimCity 4\sc4pac\cicdec\Install NYBT 41 Park Avenue (Maxis Nite)\4Model already exists. Overwrite? [y]es | [N]o | [r]ename | [a]lways | n[e]ver | rename a[l]l
y
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
5/11    .dat
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
6/11    dat
[WARNING] Failed to decompress file, exception was Ongeldige Win32 FileTime.
7/11    images\Dark Night.jpg
8/11    images\Day.jpg
9/11    images\Night.jpg
10/11   NYBT 41 Park Avenue Read Me.html
11/11   NYBT Banner01.png
[WARNING] 6 files failed to extract
```

Looks like it fails to extract the .dat files. I'm wondering whether this is just a Windows issue, or an issue with cicdec.

### CODE REVIEW

**Comment by memo33** [comment]
> could you check if this happens with you on Linux as well?

Yes, the same happens for me as well. Maybe it's an issue with the installer, as it looks like there are four files of the same name. I think it would make sense to repackage it.

**Comment by sebamarynissen** [comment]
Ok thanks for clarifying that.

By repackaging, you mean getting someone to upload a .zip to Simtropolis right? I was thinking that as a workaround we could just use the DN version for the MN here as well, just like with #35.

**Comment by memo33** [comment]
> By repackaging, you mean getting someone to upload a .zip to Simtropolis right? I was thinking that as a workaround we could just use the DN version for the MN here as well, just like with #35.

Running the installer works fine, so packaging the MN files would be preferable. Either by updating the STEX file or… I've also attached some fixes for a few borked files [here](https://github.com/memo33/sc4pac-tools/releases/tag/0.1.0).

**Comment by sebamarynissen** [comment]
I've repackaged the BAT in question here: [NYBT 41 Park Avenue (Maxis Nite).zip](https://github.com/user-attachments/files/17604707/NYBT.41.Park.Avenue.Maxis.Nite.zip). Not sure if it can be downloaded from the URL provided by GitHub (I suspect GitHub has some measures against it). Any suggestions on where to upload it? I could also just create a dedicated repo for it myself of course, but I'm not sure if this can't be considered copyright infringement.

**Comment by memo33** [comment]
Thanks. I don't know if the attachment link works permanently. I've added it here instead: [NYBT.41.Park.Avenue.Maxis.Nite.2012.zip](https://github.com/memo33/sc4pac-tools/releases/download/0.1.0/NYBT.41.Park.Avenue.Maxis.Nite.2012.zip).

As long as we don't re-upload stuff on a large scale, but only with good intentions to resolve edge cases, it's probably fine.

**Comment by sebamarynissen** [comment]
Thanks, I updated it in the yaml. Seems to work now.

**Pull request merged**
