### PR TITLE
Add RRetail's content

### PR DESCRIPTION
**Pull request by sebamarynissen**
This PR adds all of RRetail's content, except for a few with unavailable dependencies. It also excludes a few relots that rely on a large amount of ancient dependencies, which I've deemed too many to include for now.

~~Filed as a draft PR for now because I still need to test them in game, and probably linting errors will need to be fixed as well.~~ Tested in game, see comments below.

rretail

<details>

<summary>List of packages in json format</summary>

```json
"rretail:ac-moore-arts-crafts",
"rretail:acme-market",
"rretail:afc-urgent-care",
"rretail:albertsons",
"rretail:aldi",
"rretail:ashley-homestore",
"rretail:aspen-dental",
"rretail:at-home",
"rretail:auto-zone",
"rretail:belk",
"rretail:best-buy",
"rretail:bi-lo-supermarket",
"rretail:bjs-wholesale-club",
"rretail:bon-ton",
"rretail:boscovs",
"rretail:boston-store",
"rretail:canadian-tire",
"rretail:car-wash-pack",
"rretail:carsons",
"rretail:chase-bank",
"rretail:child-world",
"rretail:cinemark",
"rretail:city-center-shopping-plaza",
"rretail:coastal-crossings-shopping-center",
"rretail:cub-foods",
"rretail:cvs-pharmacy",
"rretail:discount-tire-co",
"rretail:dollar-general",
"rretail:dollar-tree",
"rretail:downingtown-plaza",
"rretail:eastview-plaza",
"rretail:elder-beerman",
"rretail:family-dollar",
"rretail:family-dollar-tree",
"rretail:family-fare-supermarket",
"rretail:fifth-thirds-bank",
"rretail:firestone-auto-center",
"rretail:flying-j-truckstop",
"rretail:food-city",
"rretail:fred-meyer",
"rretail:gas-stations-pack-vol1",
"rretail:gas-stations-pack-vol2",
"rretail:gas-stations-pack-vol3",
"rretail:gateway-shopping-center",
"rretail:giant-eagle",
"rretail:giant-md-style",
"rretail:giant-pa-style",
"rretail:grand-central-plaza",
"rretail:h-e-b-braums-dairy",
"rretail:hannaford",
"rretail:harbor-freight-tools",
"rretail:harrison-hills-village-center",
"rretail:hh-gregg",
"rretail:hy-vee",
"rretail:ingles-market",
"rretail:jewel-osco",
"rretail:keybank",
"rretail:king-street-shopping-center",
"rretail:kmart-style-1",
"rretail:kmart-style-2",
"rretail:kmart-style-3",
"rretail:kmart-supercenter",
"rretail:kroger-marketplace-brands",
"rretail:lakeview-shopping-center",
"rretail:loves-truckstop",
"rretail:lowes",
"rretail:marketplace-boulevard",
"rretail:mavis-discount-tires",
"rretail:mega-prop-pack-vol1",
"rretail:mega-prop-pack-vol2",
"rretail:mega-prop-pack-vol3",
"rretail:meijer",
"rretail:meineke-car-care",
"rretail:midas-auto-care",
"rretail:monro-mufflerbrake",
"rretail:montgomery-wards",
"rretail:motel-6",
"rretail:msm-commercial-brands",
"rretail:msm-commercial-brands-models-props",
"rretail:msm-defunct-commercial-brands-pack",
"rretail:msm-health-education-services-pack",
"rretail:northtown-plaza",
"rretail:ollies-bargain-outlet",
"rretail:oreillys-auto-parts",
"rretail:otasco-store",
"rretail:park-place-plaza",
"rretail:pathmark",
"rretail:pep-boys",
"rretail:petsmart",
"rretail:pier-1-imports",
"rretail:pilot-truckstop",
"rretail:publix",
"rretail:ralphs",
"rretail:rite-aid",
"rretail:roadside-rest-area",
"rretail:ruler-foods",
"rretail:rural-king",
"rretail:sears-auto-center-large-version",
"rretail:sears-auto-center-small-version",
"rretail:sears-hometown-store",
"rretail:sears-recycled",
"rretail:shopko",
"rretail:shopko-hometown",
"rretail:shopko-recycled",
"rretail:shoprite",
"rretail:southside-shopping-center",
"rretail:staples",
"rretail:state-street-square",
"rretail:stop-and-shop-supermarket",
"rretail:strip-mall-1",
"rretail:strip-mall-2",
"rretail:strip-mall-3",
"rretail:strip-mall-4",
"rretail:strip-mall-5",
"rretail:strip-mall-6",
"rretail:suntrust-bank",
"rretail:super-kmart-recycled",
"rretail:target-style-2",
"rretail:the-home-depot",
"rretail:the-shops-at-simtropolis",
"rretail:tops-friendly-markets",
"rretail:toys-r-us-babies-r-us",
"rretail:tractor-supply-co",
"rretail:union-square-plaza",
"rretail:video-rental-stores",
"rretail:video-stores-recycled",
"rretail:village-crossroads-mall",
"rretail:vons-shopping-center",
"rretail:walgreens",
"rretail:walgreens-cooper-design",
"rretail:walmart",
"rretail:walmart-neighborhood-market",
"rretail:walmart-recycled",
"rretail:walmart-supercenter",
"rretail:wegmans",
"rretail:weis-markets",
"rretail:wells-fargo-bank",
"rretail:western-auto",
"rretail:western-dental",
"rretail:westgate-plaza",
"rretail:winco-foods-culvers",
"rretail:winn-dixie-supermarket",
"rretail:younkers",
```

</details>

### CODE REVIEW

**Comment by sebamarynissen** [comment]
Tested the lots in game, but I noticed that the creator has done a rather sloppy job in listing the dependencies. A lot of dependencies were not listed, but it's probably gone unnoticed because they are so common - stuff like `bsc:texturepack-cycledogg-vol01` is quite common to have, but if you don't have it textures wouldn't show up for example for https://community.simtropolis.com/files/file/32405-younkers/.

I also had to exclude https://community.simtropolis.com/files/file/35468-meadowbrook-plaza/ due to brown boxes. I've investigated, but it looks like it's a "private model" that is missing that was not bundled with the package. I might upload a fix for this to the STEX and then I can re-include it.

Anyway, it's ready for review now @memo33, but I imagine it's going to take a while due to the amount of files. 

rretail

By the way, if you'd like the complete list in json format so you can easily add it to your sc4pac-plugins.json file to test, here you go:

```json
    "rretail:ac-moore-arts-crafts",
    "rretail:acme-market",
    "rretail:afc-urgent-care",
    "rretail:albertsons",
    "rretail:aldi",
    "rretail:ashley-homestore",
    "rretail:aspen-dental",
    "rretail:at-home",
    "rretail:auto-zone",
    "rretail:belk",
    "rretail:best-buy",
    "rretail:bi-lo-supermarket",
    "rretail:bjs-wholesale-club",
    "rretail:bon-ton",
    "rretail:boscovs",
    "rretail:boston-store",
    "rretail:canadian-tire",
    "rretail:car-wash-pack",
    "rretail:carsons",
    "rretail:chase-bank",
    "rretail:child-world",
    "rretail:cinemark",
    "rretail:city-center-shopping-plaza",
    "rretail:coastal-crossings-shopping-center",
    "rretail:cub-foods",
    "rretail:cvs-pharmacy",
    "rretail:discount-tire-co",
    "rretail:dollar-general",
    "rretail:dollar-tree",
    "rretail:downingtown-plaza",
    "rretail:eastview-plaza",
    "rretail:elder-beerman",
    "rretail:family-dollar",
    "rretail:family-dollar-tree",
    "rretail:family-fare-supermarket",
    "rretail:fifth-thirds-bank",
    "rretail:firestone-auto-center",
    "rretail:flying-j-truckstop",
    "rretail:food-city",
    "rretail:fred-meyer",
    "rretail:gas-stations-pack-vol1",
    "rretail:gas-stations-pack-vol2",
    "rretail:gas-stations-pack-vol3",
    "rretail:gateway-shopping-center",
    "rretail:giant-eagle",
    "rretail:giant-md-style",
    "rretail:giant-pa-style",
    "rretail:grand-central-plaza",
    "rretail:h-e-b-braums-dairy",
    "rretail:hannaford",
    "rretail:harbor-freight-tools",
    "rretail:harrison-hills-village-center",
    "rretail:hh-gregg",
    "rretail:hy-vee",
    "rretail:ingles-market",
    "rretail:jewel-osco",
    "rretail:keybank",
    "rretail:king-street-shopping-center",
    "rretail:kmart-style-1",
    "rretail:kmart-style-2",
    "rretail:kmart-style-3",
    "rretail:kmart-supercenter",
    "rretail:kroger-marketplace-brands",
    "rretail:lakeview-shopping-center",
    "rretail:loves-truckstop",
    "rretail:lowes",
    "rretail:marketplace-boulevard",
    "rretail:mavis-discount-tires",
    "rretail:mega-prop-pack-vol1",
    "rretail:mega-prop-pack-vol2",
    "rretail:mega-prop-pack-vol3",
    "rretail:meijer",
    "rretail:meineke-car-care",
    "rretail:midas-auto-care",
    "rretail:monro-mufflerbrake",
    "rretail:montgomery-wards",
    "rretail:motel-6",
    "rretail:msm-commercial-brands",
    "rretail:msm-commercial-brands-models-props",
    "rretail:msm-defunct-commercial-brands-pack",
    "rretail:msm-health-education-services-pack",
    "rretail:northtown-plaza",
    "rretail:ollies-bargain-outlet",
    "rretail:oreillys-auto-parts",
    "rretail:otasco-store",
    "rretail:park-place-plaza",
    "rretail:pathmark",
    "rretail:pep-boys",
    "rretail:petsmart",
    "rretail:pier-1-imports",
    "rretail:pilot-truckstop",
    "rretail:publix",
    "rretail:ralphs",
    "rretail:rite-aid",
    "rretail:roadside-rest-area",
    "rretail:ruler-foods",
    "rretail:rural-king",
    "rretail:sears-auto-center-large-version",
    "rretail:sears-auto-center-small-version",
    "rretail:sears-hometown-store",
    "rretail:sears-recycled",
    "rretail:shopko",
    "rretail:shopko-hometown",
    "rretail:shopko-recycled",
    "rretail:shoprite",
    "rretail:southside-shopping-center",
    "rretail:staples",
    "rretail:state-street-square",
    "rretail:stop-and-shop-supermarket",
    "rretail:strip-mall-1",
    "rretail:strip-mall-2",
    "rretail:strip-mall-3",
    "rretail:strip-mall-4",
    "rretail:strip-mall-5",
    "rretail:strip-mall-6",
    "rretail:suntrust-bank",
    "rretail:super-kmart-recycled",
    "rretail:target-style-2",
    "rretail:the-home-depot",
    "rretail:the-shops-at-simtropolis",
    "rretail:tops-friendly-markets",
    "rretail:toys-r-us-babies-r-us",
    "rretail:tractor-supply-co",
    "rretail:union-square-plaza",
    "rretail:video-rental-stores",
    "rretail:video-stores-recycled",
    "rretail:village-crossroads-mall",
    "rretail:vons-shopping-center",
    "rretail:walgreens",
    "rretail:walgreens-cooper-design",
    "rretail:walmart",
    "rretail:walmart-neighborhood-market",
    "rretail:walmart-recycled",
    "rretail:walmart-supercenter",
    "rretail:wegmans",
    "rretail:weis-markets",
    "rretail:wells-fargo-bank",
    "rretail:western-auto",
    "rretail:western-dental",
    "rretail:westgate-plaza",
    "rretail:winco-foods-culvers",
    "rretail:winn-dixie-supermarket",
    "rretail:younkers",
```

**Comment by sebamarynissen** [comment]
I [added a fix for Meadowbrook Plaza to the STEX](https://community.simtropolis.com/files/file/36596-meadowbrook-plaza-fixed/) and included this as well in the metadata, so Meadowbrook Plaza is now included again.

**Comment by sebamarynissen** [comment]
@memo33 I was thinking, would you prefer that these kinds of huge contributions get included on the [Simtropolis channel](https://github.com/sebamarynissen/simtropolis-channel) instead? There's a few benefits to this, because the quality requirements on the Simtropolis channel are lower than you aim for with the default channel. More specifically, I'm talking about the fact that I wouldn't have to alter the decription to pass the no ego perspective rule. It would also relieve you of the task of having to review 200+ packages.

I'm considering "backfilling" the Simtropolis channel anyway with as much existing content as possible. The default channel could then be mainly used for dependency packages and a high-quality, manually curated list of plugins, that can even be pulled in from the Simtropolis channel in a way.

**Comment by memo33** [comment]
Yeah, I think that would make a lot of sense. I'm a bit overwhelmed by these large pull requests. It's great to see all these new additions, but considering the metadata is largely assembled using automation, these packages might fit in better on the Simtropolis channel. It's particularly difficult to review these when the dependency lists on the STEX entries are incomplete - it also makes it hard to manually maintain this channel.

I'd like to tackle the backlog of pull requests. Could you perhaps go through your PRs and check which ones are ready for review? Otherwise, if you still plan to make changes, you could set them to Draft.

**Comment by sebamarynissen** [comment]
Closing in favor of https://github.com/sebamarynissen/simtropolis-channel/pull/49.

**Pull request closed without merging**
