### PR TITLE
Add MushyMushy, Angry Mozart, KOSC dependencies

### PR DESCRIPTION
**Pull request by noah-severyn**

### CODE REVIEW

**Comment by noah-severyn** [comment]
What am I missing here? I don't quite understand this error.

**Comment by memo33** [comment]
> What am I missing here? I don't quite understand this error.
> 
> > The following assets have the same URL:
> > supershk-mega-parking-textures, kingofsimcity-supershk-mega-parking-textures
> > supershk-fa3-parking-textures, kingofsimcity-supershk-fa3-parking-textures

The assets have been defined twice under different names. The second copy is redundant – you can use the existing assets instead that are already defined in [src/yaml/supershk/mega-parking-textures.yaml](https://github.com/memo33/sc4pac/blob/main/src/yaml/supershk/mega-parking-textures.yaml).

**Comment by noah-severyn** [comment]
> > What am I missing here? I don't quite understand this error.
> > > The following assets have the same URL:
> > > supershk-mega-parking-textures, kingofsimcity-supershk-mega-parking-textures
> > > supershk-fa3-parking-textures, kingofsimcity-supershk-fa3-parking-textures
> 
> The assets have been defined twice under different names. The second copy is redundant – you can use the existing assets instead that are already defined in [src/yaml/supershk/mega-parking-textures.yaml](https://github.com/memo33/sc4pac/blob/main/src/yaml/supershk/mega-parking-textures.yaml).

Ok thanks that makes sense I didn't think to look for it under that name. Removed those for now and tests are passing. Was there a specific reason for a group of supershk instead of kingofsimcity?

**Comment by memo33** [comment]
> Was there a specific reason for a group of supershk instead of kingofsimcity?

No, not really. It was partially due to my lack of understanding whether supershk is a modding team and partially due to aiming for consistency with naming of other dependency packs, which don't necessarily have an author name as group.

**Comment by noah-severyn** [comment]
> > Was there a specific reason for a group of supershk instead of kingofsimcity?
> 
> No, not really. It was partially due to my lack of understanding whether supershk is a modding team and partially due to aiming for consistency with naming of other dependency packs, which don't necessarily have an author name as group.

I'd say SuperSHK is a 'brand' as opposed to a modding group as it's pretty much strictly a kingofsimcity project. In my opinion, and in this case, it would make more sense to have author and group both as kingofsimcity -- though that's probably a change suitable for a different PR if you agree.

**Comment by memo33** [comment]
Certainly worth considering. Currently, there's no non-intrusive way of renaming packages that doesn't require manual intervention by users who have already installed those packages, so for the time being at least it's better to keep the current names (until a renaming feature is implemented in sc4pac).

**Comment by memo33** [comment]
Regarding the Angry Mozart freight cars: As this is one of the largest dependency packs out there, is this typically required in full or could it reasonably be split into smaller packages? My guess is this isn't easily possible, but maybe you know more about its use.

Regarding the KOSC logistics essentials: The package overrides some of MushyMushy's files and therefore needs to load after them. It could be moved to `900-overrides`.
(Technically this is quite subtle, as the KOSC files are .dat files that override MushyMushy's .sc4desc files – and .dat files always load after other file types – but it becomes a problem when datpacking the plugins folder.)

**Comment by noah-severyn** [comment]
I was wondering about package renaming but kind of figured that was the case.

I have made the change to split the train props out to 10 additional packages based on the car type. It was nicely broken out like that in the user manual so I just duplicated that scheme. To my knowledge it has only been used on a few lots - some lots like sidings use a wide variety of cars while some industrial lots would only use one type. I kept the main whole package, but added a note recommending one of the smaller more specialized packages instead.

Fixed the logistics essentials subfolder.

Sorry for all the typos ... still working things out with my tool but its getting better. :)

**Comment by memo33** [comment]
Thanks for the changes. I've made one more change that adds the individual specialized packages as dependencies of the full Angry Mozart package, so that the full package is just a collection of the smaller ones. I'm going to merge the PR when ST is back online.

**Pull request merged**
