### PR TITLE
add andisart sunken lots

### PR DESCRIPTION
**Pull request by noah-severyn**
Add andisart sunken lots and my remake of them. I'm picking up on more of the syntax; feel free to correct anything still wrong. :)

### CODE REVIEW

**Comment by noah-severyn** [comment]
Fixed some errors. Not sure what the remaining ones are.

**Comment by memo33** [comment]
Thanks. I've fixed the lint error. The `include` properties are defined for each individual asset in the list of `assets`, so they need to be indented.

A few thoughts:

The `nos17:sunken-lots` seems to use the wrong asset.

I'm not sure splitting the lots into eyecandy/functional is really needed. If someone decides to install them, I think it would be fine to have all 5 lots, so I'd prefer to merge the two packages into one to reduce complexity.

The summaries could include a bit more information that distinguishes the packages (as long as the summaries are reasonably short), as only the summary is shown on the main channel page.

Also, you can refer to additional optional packages in the description to point out that they exist and can be installed as well. Using the syntax ``` `pkg=andisart:sunken-lots-eyecandy` ``` creates a hyperlink.

Also consider releasing your stuff on the STEX for discoverability. This would also help with maintainability of the metadata, as it's more likely that checking version numbers and last-modified timestamps for updates will be automated for STEX files than for forum attachments (currently this is only implemented for SC4E, not ST yet).

**Comment by memo33** [comment]
What happened?

**Comment by noah-severyn** [comment]
I must have messed something up and closed by accident. I agree with you on the changes and I'll reopen once I make them.

**Pull request closed without merging**
