### PR TITLE
Add `mattb325:transportation-collection`

### PR DESCRIPTION
**Pull request by sebamarynissen**
This PR adds mattb325's entire [transportation collection](https://www.sc4evermore.com/index.php/downloads/download/19-transportation/315-sc4d-lex-legacy-mattb325-transportation-collection-darknite).

image

### CODE REVIEW

**Comment by memo33** [comment]
There seem to be quite a lot of differences between the dependencies listed here in the metadata vs the Readme or STEX entries. Are you really sure these are all correct?

My concern is that some of these dependencies might not really be needed. Maybe some referenced prop files are included in multiple megapacks. Or maybe some props are overrides of Maxis content. Both cases might lead to redundant dependencies.

I've commented on a few dependency lists, but haven't examined all of them.

**Comment by sebamarynissen** [comment]
I will verify it again. There are probably a bunch of dependencies that aren't strictly required. The reason is that my dependency tracking script used to collect dependencies that weren't really "hard" dependencies. For example, sometimes a bsc package adds objects to the default Maxis families - think of car props for example. When one of the packages then uses those families, the bsc package that added those props to the family gets marked as a dependency, but it won't result in brown boxes if it's not installed.

I have updated my dependency tracking script in the meantime, so it should no longer include those things. I will run it again on these, that should probably eliminate a lot of the unneeded dependencies.

**Comment by memo33** [comment]
Ah, when props are added to Maxis families, there's always the chance that this is accidental, not intentional. This can happen when you duplicate an existing Maxis prop and assign a unique ID, but don't delete the prop family property. I'm guilty of exactly that. I duplicated a Maxis light pole to "fix" a bug, but didn't think of removing it from the family. As a result, the new prop appeared in all sorts of places where it shouldn't, messing up T21 patterns and such. The wrong behavior was observed by many people, but it took a decade to fix the actual issue.

**Comment by sebamarynissen** [comment]
Ah I see. In any case, for my dependency tracking it doesn't really matter anymore because if I detect that Maxis objects are present in a family, it doesn't label all the other ones as a dependency (see [this code](https://github.com/sebamarynissen/sc4/blob/e0e6d1850abc37400b5a70b218e48bb995e8809b/src/plugins/dependency-tracker.ts#L438).

However, I've also noticed that for example the jim carprop pack intentionally disables the Maxis car props, so in that case, if you have that prop pack in your plugins folder, and a lot uses Maxis car props, then suddenly jim carprop pack is labeled as a dependency. I've verified that PIM-X works in the same way by the way.

For the jim carprop pack - needed for #50 - I solved this by excluding the file that disables the Maxis cars iirc.

**Comment by sebamarynissen** [comment]
@memo33 Can you check the url-check action? It looks like it's failing because there are no STEX urls in the file.

**Comment by sebamarynissen** [comment]
Pretty strange indeed.

Anyway, I think I fixed the dependencies. I seriously messed up with my tracking script before so it seems, and I also added certain assets where they should actually have been dependencies. The reason why SimFox's day and nite mod was listed as an explicit dependency was that it overrides certain Maxis light cones, so it got tracked as a dependency. Should be fixed now.

**Comment by memo33** [comment]
Excellent. Seems to work well. Thanks a lot. Does that mean it would make sense to revisit the dependencies of the already merged PRs or would they be unaffected?

**Comment by sebamarynissen** [comment]
I'm not sure. I will run the updated script on them as well.

I think the impact will be limited though, as it seems the main problem was that I incorrectly included an asset where it should've been a dependency (see https://github.com/memo33/sc4pac/pull/43/commits/11ccf74b05d962d075797a6d6217489585541e5e#diff-72702f112b07d049fc10a776c34656dff2ab3fc18b8bb2c4eca327b8c7f0cf76L132 for example), which triggered a waterfall of dependencies. Hence I think the already merged PRs won't really be affected.

**Comment by sebamarynissen** [comment]
@memo33 See #59 for a PR removing a bunch of unneeded dependencies from the residential collection.

**Comment by memo33** [comment]
> @memo33 Can you check the url-check action? It looks like it's failing because there are no STEX urls in the file.

I've just fixed it in https://github.com/memo33/sc4pac-actions/commit/d8f1640ca79c4d147a365ba3b9b5150640a4551d. The `url-check` failures were caused by `git diff --no-index` returning non-zero exit codes in case of differences.

**Pull request merged**
