### PR TITLE
B62 remastered content

### PR DESCRIPTION
**Pull request by noah-severyn**

### CODE REVIEW

**Comment by memo33** [comment]
Please make sure to test the installation of the packages, especially ensuring that all the desired files get extracted and installed. You know best whether the installed files are complete. This cannot be automated, so needs to be tested manually. You can build the channel locally using `sc4pac channel build --output my-local-channel src/yaml` and then add it for testing `sc4pac channel add "file:///C:/absolute/path/to/my-local-channel"`.

One more thing I noticed: In YAML, the `>` character indicates that text is wrapped, so to add a linebreak one needs to separate paragraphs by an empty line (i.e. 2 linebreaks). Use `|` if you want to preserve all linebreaks.

**Comment by noah-severyn** [comment]
I did forget we could test. I'll let you know again here when I've been through everything.

**Comment by noah-severyn** [comment]
@memo33 Everything tested ok. This should be good to close and merge now.

**Comment by memo33** [comment]
I'm currently working on some updates for this PR (after just having integrated the STEX API into GH Actions).

The STEX description of the Sears Grand lists "BSC Mega Props - KevDan25 Vol01" as dependency which is missing in your metadata. Intentionally?

**Comment by memo33** [comment]
Your scripts seem to garble up text containing double quotes.

Also, for the verizon tower, I'm going to remove the takemethere:mount-royal-transmission-tower dependency. It seems redundant as you already extract the corresponding asset itself.

**Comment by memo33** [comment]
The pond variant of b62:sears-grand seems to install lots only. Which files would be correct here?
```
300-commercial/b62.sears-grand.pond.3.sc4pac/
├── PLOP_16x13_B62-PLOP_SearsGrand_MB v.3.41_166d1f2b.SC4Lot
├── PLOP_19x9_B62-PLOP_SearsGrand_Pond-Parking_a66d2090.SC4Lot
└── PLOP_3x13_B62-PLOP_SearsGrand_Pond_2673947c.SC4Lot
```


---

Ok, I've made my changes. Other than the points mentioned above, this is good to go if you are happy with the changes. (The CI is broken currently for reasons unrelated to this PR.)

Among other things, I've removed most of the stats as they are pretty useless, so there's no point of keeping track of them here in this repository.

**Comment by noah-severyn** [comment]
1. On the descriptions, it's clear you're favoring shorter ones. I will note this for the future and rewrite the STEX entry descriptions for brevity. Removing the stats is fine.
2. KevDan25 Vol01 is incorrectly missing - fixed
3. Transmission tower - noted
4. b62.sears-grand.pond.3 should also be installing models - fixed.

**Comment by noah-severyn** [comment]
Alright hopefully that should fix it - updated the STEX entry. Thank you for your patience with this memo.

**Comment by memo33** [comment]
Thanks for the fixes. Still something is wrong with the STEX upload, as it contains all the files twice.
```
B62-SearsGrand
├── B62-SearsGrand
│   ├── b62 pylonsign-searsgrand v.1.1-0x5ad0e817_0x50ec22ad_0x490000.SC4Model
│   ├── b62 pylonsign-searsgrand v.1.1-0x6534284a-0x50ec22ad-0xf16a3219.SC4Desc
│   ├── B62-SearsGrand
│   │   ├── b62 pylonsign-searsgrand v.1.1-0x5ad0e817_0x50ec22ad_0x490000.SC4Model
│   │   ├── b62 pylonsign-searsgrand v.1.1-0x6534284a-0x50ec22ad-0xf16a3219.SC4Desc
│   │   ├── b62_SearsGrand_MB v.3.41-0x5ad0e817_0x50ec22ad_0x470000.SC4Model
│   │   ├── b62_SearsGrand_MB v.3.41-0x6534284a-0x50ec22ad-0xd16a0a76.SC4Desc
│   │   ├── b62 Shell_DrinkCenter v 1.1-0x5ad0e817_0x131ed1ac_0x30000.SC4Model
│   │   ├── b62 Shell_DrinkCenter v 1.1-0x6534284a-0x50ec22ad-0xf3217655.SC4Desc
│   │   ├── b62 Shell_MIGM v 1.2-0x5ad0e817_0xf31d9579_0x30000.SC4Model
│   │   ├── b62 Shell_Pylon_TSign v 2.1-0x5ad0e817_0xf31e7fe0_0x30000.SC4Model
│   │   ├── b62 Shell_Pylon_TSign v 2.1-0x6534284a-0x50ec22ad-0x33212331.SC4Desc
│   │   ├── PROP_b62 Shell_MIGM v 1.2-0x6534284a-0xd1e3b8fd-0x13194fdd.SC4Desc
│   │   └── PROP_Zaxby's-0x6534284a-0xd1e3b8fd-0x131ad2be.SC4Desc
│   ├── b62_SearsGrand_MB v.3.41-0x5ad0e817_0x50ec22ad_0x470000.SC4Model
│   ├── b62_SearsGrand_MB v.3.41-0x6534284a-0x50ec22ad-0xd16a0a76.SC4Desc
│   ├── b62 Shell_DrinkCenter v 1.1-0x5ad0e817_0x131ed1ac_0x30000.SC4Model
│   ├── b62 Shell_DrinkCenter v 1.1-0x6534284a-0x50ec22ad-0xf3217655.SC4Desc
│   ├── b62 Shell_MIGM v 1.2-0x5ad0e817_0xf31d9579_0x30000.SC4Model
│   ├── b62 Shell_Pylon_TSign v 2.1-0x5ad0e817_0xf31e7fe0_0x30000.SC4Model
│   ├── b62 Shell_Pylon_TSign v 2.1-0x6534284a-0x50ec22ad-0x33212331.SC4Desc
│   ├── KEEP ONE ... Diggis Version
│   │   ├── PLOP_16x13_B62-PLOP_SearsGrand_MB v.3.41_166d1f2b.SC4Lot
│   │   ├── PLOP_19x9_B62-PLOP_SearsGrand_Pond-Parking_a66d2090.SC4Lot
│   │   └── PLOP_3x13_B62-PLOP_SearsGrand_Pond_2673947c.SC4Lot
│   ├── KEEP ONE ... Non-Diggis Version
│   │   ├── B62-PLOP_SearsGrand_Parking-0x6534284a-0xd3a3e650-0xb6740c84.SC4Desc
│   │   ├── PLOP_14x13_B62-PLOP_SearsGrand_MB v.3.41_e66b1122.SC4Lot
│   │   └── PLOP_16x9_B62-PLOP_SearsGrand_NoPond-Parking_766b0f9d.SC4Lot
│   ├── PROP_b62 Shell_MIGM v 1.2-0x6534284a-0xd1e3b8fd-0x13194fdd.SC4Desc
│   ├── PROP_Zaxby's-0x6534284a-0xd1e3b8fd-0x131ad2be.SC4Desc
│   └── Read Me - Sears Grand.txt
├── KEEP ONE ... Diggis Version
│   ├── PLOP_16x13_B62-PLOP_SearsGrand_MB v.3.41_166d1f2b.SC4Lot
│   ├── PLOP_19x9_B62-PLOP_SearsGrand_Pond-Parking_a66d2090.SC4Lot
│   └── PLOP_3x13_B62-PLOP_SearsGrand_Pond_2673947c.SC4Lot
├── KEEP ONE ... Non-Diggis Version
│   ├── B62-PLOP_SearsGrand_Parking-0x6534284a-0xd3a3e650-0xb6740c84.SC4Desc
│   ├── PLOP_14x13_B62-PLOP_SearsGrand_NoPond_e66b1122.SC4Lot
│   └── PLOP_16x9_B62-PLOP_SearsGrand_NoPond-Parking_766b0f9d.SC4Lot
└── Read Me - Sears Grand.txt

8 directories, 36 files
```

**Comment by noah-severyn** [comment]
Shit. Fixed. Thank you.

**Comment by memo33** [comment]
Let's goooo.

**Pull request merged**
