### PR TITLE
Add `mattb325:residential-houses` and `mattb325:residential-multi-unit-pack`

### PR DESCRIPTION
**Pull request by sebamarynissen**
This PR adds mattb325's [entire set of 55 residentials](https://www.sc4evermore.com/index.php/downloads/download/11-residential/100-sc4d-lex-legacy-mattb325-residential-houses-pack-darknite) to the channel.

The metadata has been generated with a script that detects the dependencies automatically. That was needed because the download on SC4Evermore just lists the [BSC common dependencies pack](https://www.sc4evermore.com/index.php/downloads/download/22-dependencies/3-sc4d-lex-legacy-bsc-common-dependencies-pack) which kind of defeats the purpose of using sc4pac as you don't need the entire bsc set for this pack, only a few.

Some images for fun:

image

image

image

### CODE REVIEW

**Comment by memo33** [comment]
Wow, that's amazing. Thanks. I had completely given up on those files.

How confident are you that the dependencies are correct and complete? Did you parse the lot config properties for relevant IDs?

Those early SC4E files were put together in a rush. While the DN file includes a couple of original Readme files listing dependencies, a lot of info seems to be missing. Probably your work here will help getting the info up on SC4E as well.

**Comment by sebamarynissen** [comment]
I'm fairly confident that they are correct and complete. At my first try, I suffered from a lot of brown boxes. Then I dug a bit into the inner workings of SimCity 4 and found out that my script wasn't tracking the models. I learned that this was referenced by the resource key types, and tracking this down too I was able to get rid of the brown boxes.

Obviously it's harder to figure out whether all prop dependencies are there too because they simply don't show up instead of a brown box. The lots that I tested were looking fine, though I was not able to test and inspect all 55 of them in detail.

If you're interested in the dependency tracking code, you can find this [here](https://github.com/sebamarynissen/sc4pac-helpers/tree/main/lib/dependency-tracker.js)

I'm also working on the multi-unit set, though here my code still results in a few brown boxes. Maybe you could wait to merge this PR until I have figured out if something still needs to be changed. I'm away this weekend, but I plan to work on it further on Monday.

**Comment by sebamarynissen** [comment]
I've added the [multi-unit pack](https://www.sc4evermore.com/index.php/downloads/download/11-residential/99-sc4d-lex-legacy-mattb325-residential-multi-unit-pack-maxisnite) as well using the same strategy of manually tracking dependencies.

I've also ensured that my script finds every building, prop or texture referenced from any of the files (including from the SimCity_*.dat) and it is able to find everything. I've also done some more tests, and everything looks good to me.

**Comment by sebamarynissen** [comment]
I noticed that a lot of the individual packages from the multi-unit pack could also be found on Simtropolis, so I referenced to Simtropolis and used the images from there where possible instead.

**Comment by noah-severyn** [comment]
> Obviously it's harder to figure out whether all prop dependencies are there too because they simply don't show up instead of a brown box. The lots that I tested were looking fine, though I was not able to test and inspect all 55 of them in detail.
> 
> If you're interested in the dependency tracking code, you can find this [here](https://github.com/sebamarynissen/sc4pac-helpers/tree/main/lib/dependency-tracker.js)

If you're interested, to find the prop and texture dependencies on a lot you could run the LotObject IIDs against the [Prop Texture Catalog database](https://github.com/noah-severyn/SC4PropTextureCatalog/blob/main/Data/Catalog.db), an sqlite db. It's a bit out of date as it hasn't been updated since the BSC Common Dependencies was released, but it might give you a good enough idea anyways. Updating it is on my todo list.

**Comment by sebamarynissen** [comment]
Makes sense to go for "2 R$$ houses on low-density lots". I will change it. I didn't really know what to put in the description as there is not much information about the individual packages on SC4E, and I didn't really feel like writing a description manually for all these packages.

Not sure about the summary, I would personally keep it in the description, but let me know what you want.

I agree to rename them to collections as well, keeps them in line nicely indeed with the other collections already on the channel.

**Comment by memo33** [comment]
> I didn't really know what to put in the description as there is not much information about the individual packages on SC4E, and I didn't really feel like writing a description manually for all these packages.

Ok, that's understandable.

> Not sure about the summary, I would personally keep it in the description, but let me know what you want.

Alright, let's keep the summaries as is, then.


One more unrelated thought. The residential and commercial subfolders are filling up now, which is great to see. In the long run, it probably makes sense to split them up into smaller folders, but I'm not sure if dividing by wealth or dividing by density is preferable. Some files would be difficult to categorize. Even now some packages include residential and commercial buildings simultaneously.

**Comment by sebamarynissen** [comment]
I made the changes we discussed. About splitting them up into smaller folders, I see why you would do that, but the difficulty is always that it's hard to choose a single parameter to categorize them on. Wealth and density are obvious candidates, but still I'm not sure if it's worth it. For example, in Aarom Graham's collection, lots often have two wealth types: CS$$ and CS$$$ for example, so in that case categorizing by wealth is hard.

**Comment by sebamarynissen** [comment]
One additional thing about this: I noticed that there are sometimes small discrepancies between the MN and DN versions in the folder structure. For example, sometimes a folder name has no spaces (`CamelCase`) in the MN pack, but `Camel Case` in the DN pack. Would it make sense to use regexes for this as much as possible (`Camel ?Case`) so that if the pack is updated later on with a slightly different folder structure it doesn't suddenly break?

**Comment by sebamarynissen** [comment]
I wonder if it would help if we start advocating for sc4pac more so that creators of packages know what the implications can be of updating their folder structure. In an ideal (not so far) future, sc4pac will be the default way of installing plugins anyway, and plugins should - in my opinion - be designed for this. For example, there is really no need anymore for those Java installers when using sc4pac (except for stuff like the NAM of course), so when sc4pac is widely used, I don't think installers should still be created.

**Comment by sebamarynissen** [comment]
If you give me a few minutes, I'll push a change with inclusion patterns that are better prepared for changes.

**Comment by memo33** [comment]
Of course.

**Comment by sebamarynissen** [comment]
Looks like that file from the shared resources is nowhere referenced, so everything looks fine. Lgtm. 👍

**Comment by memo33** [comment]
Let's go.

**Pull request merged**
