### PR TITLE
add Appalachian Terrain Mod

### PR DESCRIPTION
**Pull request by jflann**
Adds lowkee33's Appalachian Terrain Mod and LK Starter Set beach, rock, and water textures.  The complete install depends on the starter set, whose components are also individually installable.

### CODE REVIEW

**Comment by memo33** [comment]
Thanks. I'm considering to drop the `lowkee33:lk-starter-set` and just directly depend on the beach, rock and water packages, as the starter set itself seems of limited use. For anyone looking for customization options, directly choosing beach, rock and water seems more transparent.

Also, would it make sense to rename these packages to `lowkee33:appalachian-terrain-mod-beach` etc. to make clear their purpose, or are these used by other terrain mods as well? (If I recall correctly, not all rock textures can be mixed and matched with all terrain mods due to different tiling factor settings, which applies particularly to the Appalachian terrain mod.)

One more detail: Although technically not needed, I like to keep the package version number in sync with the asset version number, as only the former is visible to the end user, so if the versions match it's easier to see that the package is up-to-date with the original file.

**Comment by jflann** [comment]
The reason I kept the "LK Starter Set" names is because prior to the LEX reorganization, it used to be a separate download and people might search for it by that name.  I made sure to put "Appalachian Terrain Mod" in the description so it shows it up that search as well.  To be honest, I'm not sure which name would be best.  My thought was preserving the original names, but now they are all one download, so maybe it makes more sense to name them as you suggested.  I don't have a strong opinion on it, so whichever you think is best works for me.

Thanks for the clarification on the version numbers, I was a bit uncertain about that.

**Comment by jflann** [comment]
One more thought, should the "cliff" package be renamed to "rock"?  They seem to more commonly be referred to as rock mods.

**Comment by memo33** [comment]
Ok, I've renamed the packages. The search command currently only searches for words contained in the summary or the package identifier (but not in the description). That's why I sometimes include specific words or abbreviations in the summary that might be used in a search. Now, these packages come up when searching for "starter set" or "appalachian terrain".

**Pull request merged**
