### PR TITLE
Add Simmer2's content

### PR DESCRIPTION
**Pull request by sebamarynissen**
This PR adds most of [Simmer2's content](https://community.simtropolis.com/profile/444001-simmer2/content/?type=downloads_file&sortby=file_submitted&sortdirection=desc) (250+ packages). I had to leave out a few ones due to dependencies not being available (for example, one package relies on a building made by WolfZe, other packages rely on SC4D LEX dependencies that are not yet available on SC4E).

A few things to note here:
 - I've added everything under the name `sm2`, even though a package under the name `simmer2` already exists in the default channel. If you want me to change everything to `simmer2`, just let me know and I'll run a script that does this automatically.
 - ~~Some packages rely on dependencies from other PRs - most notably #48 - so the tests will fail as long as these PRs haven't been merged.~~ Fixed since #51.
 - ~~In order to add all this content, I had to add a few dependency packages that weren't available in the default channel too. If you want I can extract these into a separate PR so that the dependencies can be merged asap, while the review of Simmer2's actual content can take more time.~~ See #51.
 - I did my best to automatically parse the descriptions from Simtropolis. For example, any dependencies listed in the description have been filtered out etc. Some descriptions have been revamped a little manually (in order to pass the "no I or my" linting rule), but it was not feasible to manually write a description for all these packages.

simmer2

<details>

<summary>List of packages in json format</summary>

```json
[
  "sm2:2-stories-brick-row-houses",
  "sm2:3-bay-engine-house",
  "sm2:3600-bc-stonehenge",
  "sm2:56-glendale-st",
  "sm2:58-glendale-st",
  "sm2:5g-cell-tower",
  "sm2:60-glendale-st",
  "sm2:60s-freight-and-livestock-railyard",
  "sm2:62-glendale-st",
  "sm2:64-glendale-st",
  "sm2:abandoned-rail-yard",
  "sm2:abandoned-train-stop",
  "sm2:adm-grain-elevator-hd",
  "sm2:adm-grain-elevator-sd",
  "sm2:advanced-solar-array",
  "sm2:agrochemicals-ltd",
  "sm2:air-purifier-facility",
  "sm2:am-radio-antenna",
  "sm2:amps-city-office",
  "sm2:amps-energy-research-facility",
  "sm2:amps-rural-maintenance-yard",
  "sm2:amps-rural-office",
  "sm2:ancient-ruins-roundabout",
  "sm2:aqueduct",
  "sm2:aquila-reale",
  "sm2:arrow-cement-precast",
  "sm2:aurelius-radio-telescope",
  "sm2:autorack-yard",
  "sm2:aziz-used-cars",
  "sm2:barrow-heliport",
  "sm2:billboards-pack-vol1",
  "sm2:bin-rentals-ltd",
  "sm2:biofuel-distillers",
  "sm2:biofuel-tanks-array-2",
  "sm2:biofuel-tanks-array-4",
  "sm2:biofuel-tanks-array-8",
  "sm2:biogas-power-plant",
  "sm2:bordens-dairy-processing-plant",
  "sm2:brass-stamping-co-grow",
  "sm2:brass-stamping-co-plop",
  "sm2:breakwater-concrete-blocks",
  "sm2:bricks-and-blocks-building-supplies",
  "sm2:brooks-farm-feed",
  "sm2:bt-tower",
  "sm2:cape-cod-lighthouse",
  "sm2:cape-hatteras-lighthouse",
  "sm2:carstar-body-shop",
  "sm2:cell-repeater-tower",
  "sm2:cell-towers",
  "sm2:center-pivot-irrigation-fields",
  "sm2:chemical-mixing-inc",
  "sm2:chemical-mixing-tanks-set",
  "sm2:chevron-gas-station-barge",
  "sm2:ciechanow-water-tower",
  "sm2:citybank",
  "sm2:co2-scrubber",
  "sm2:co2-scrubber-mini",
  "sm2:coal-barge-a",
  "sm2:coastline-marine-mmp-kit",
  "sm2:cold-fusion-reactors",
  "sm2:concrete-sound-barriers",
  "sm2:cooling-tower",
  "sm2:cooper-tires",
  "sm2:cooper-tires-grow",
  "sm2:crop-circles-vol1",
  "sm2:crown-and-pinion-gears-ltd",
  "sm2:curzon-street-stations",
  "sm2:dales-furniture-gallery",
  "sm2:danforth-train-station",
  "sm2:deepwater-oil-terminal",
  "sm2:desalination-plant",
  "sm2:diy-oil-storage",
  "sm2:dolphins-fountain",
  "sm2:doppler-radar-installation",
  "sm2:dora",
  "sm2:dry-stone-walls",
  "sm2:easy-money",
  "sm2:electromagnetic-solutions-ltd",
  "sm2:electroplating-inc",
  "sm2:enzo-aricci-boutique",
  "sm2:essentials",
  "sm2:esso-gas-station-barge",
  "sm2:ethanol-storage-tanks",
  "sm2:faro-de-santa-marta",
  "sm2:fast",
  "sm2:ferris-sculpture",
  "sm2:fire-station-44",
  "sm2:fuel-terminal",
  "sm2:garbage-transfer-station-22-dtr",
  "sm2:garbage-transfer-station-24-str",
  "sm2:garthamlock-water-tower",
  "sm2:ge-solar-power-plant",
  "sm2:georges-auto-repair",
  "sm2:geothermal-power-plant",
  "sm2:glendale-glr-station",
  "sm2:global-freight",
  "sm2:glr-spurs-vol1",
  "sm2:glycerol-distiller-facility",
  "sm2:gogar-tram-depot",
  "sm2:gravel-co",
  "sm2:greek-temple-ruin",
  "sm2:greenwood-sunken-station",
  "sm2:gulf-gas-station-barge",
  "sm2:haut-fond-prince-lighthouse",
  "sm2:hayashi-semiconductors-int",
  "sm2:heritage-roundhouse",
  "sm2:heritage-roundhouse-mv",
  "sm2:home-depot-distribution-center",
  "sm2:hot-air-balloons",
  "sm2:hot-air-balloons-vol2",
  "sm2:hump-yard",
  "sm2:hv-transformer",
  "sm2:hvac-repairs-svc",
  "sm2:hydrocarbon-distiller",
  "sm2:hydrocarbon-separator-array",
  "sm2:hydrocracking-unit",
  "sm2:hydrogen-extractor-array-x1",
  "sm2:induced-draft-cooling-towers",
  "sm2:industrial-exhaust-stack",
  "sm2:industrial-lining-ceramics",
  "sm2:intermodal-terminal",
  "sm2:jetfreight-logistics",
  "sm2:kennedy-bus-and-subway-hub",
  "sm2:kinetic-wave-energy",
  "sm2:large-water-pump-house",
  "sm2:large-water-treatment-plant",
  "sm2:limington-station",
  "sm2:loblaws-supermarket",
  "sm2:locomotive-wash-station",
  "sm2:locomotives-refueling-station",
  "sm2:longstone-lighthouse",
  "sm2:main-subway-depot",
  "sm2:main-transformers",
  "sm2:main-water-depot",
  "sm2:mann-hydrazine-manufacturing",
  "sm2:marine-wind-power",
  "sm2:markham-train-station",
  "sm2:medium-water-treatment-plant",
  "sm2:mega-prop-pack-vol1",
  "sm2:mega-prop-pack-vol2",
  "sm2:mega-prop-pack-vol3",
  "sm2:mega-prop-pack-vol4",
  "sm2:mega-prop-pack-vol5",
  "sm2:mega-prop-pack-vol6",
  "sm2:metal-coatings-inc",
  "sm2:middleport-pottery",
  "sm2:middleport-pottery-diagonal",
  "sm2:milk-and-things",
  "sm2:mobile-power-generator",
  "sm2:modular-solar-power-plant",
  "sm2:montessori-private-school",
  "sm2:neoclassic-gazebo",
  "sm2:news-kiosks",
  "sm2:newton-observatory",
  "sm2:nor-am-cold-storage",
  "sm2:nuts-vdk-swan-mill-power-plant",
  "sm2:oakland-glr-stations",
  "sm2:oakland-train-stations",
  "sm2:oil-pipeline-a-vol1",
  "sm2:oil-pipelines-vol2",
  "sm2:old-abandoned-factory",
  "sm2:old-cell-and-tv-repeater-tower",
  "sm2:old-cellular-and-tv-tower",
  "sm2:old-coal-tower-spur",
  "sm2:old-dutch-windmill",
  "sm2:old-fortresses",
  "sm2:old-texaco-stations",
  "sm2:oregon-lighthouse",
  "sm2:pacific-freight-ltd",
  "sm2:parker-cannery-co",
  "sm2:parker-cannery-company",
  "sm2:peartree-apartments",
  "sm2:perrys-victory-memorial",
  "sm2:petroleum-terminal-b",
  "sm2:plaxil-8-mdf",
  "sm2:plaxil-8-mdf-plop",
  "sm2:port-train-depot",
  "sm2:post-office-rail-depot",
  "sm2:power-pack",
  "sm2:precision-tool-design-ltd",
  "sm2:rail-corp",
  "sm2:rail-service-yard-1",
  "sm2:rail-service-yard-2",
  "sm2:railway-bits-set-vol1",
  "sm2:reddington-concrete-plant",
  "sm2:rona",
  "sm2:rotunda-apartments",
  "sm2:roundabout-sculptures-set",
  "sm2:royal-flush-plumbing-supplies",
  "sm2:rrw-hd-rail-bumpers",
  "sm2:rrw-hd-rail-bumpers-and-props",
  "sm2:rrw-nsb-tex",
  "sm2:rrw-spurs-and-siding-vol1",
  "sm2:rrw-spurs-and-sidings-vol2",
  "sm2:rusty-industry-vol1",
  "sm2:rutger-hauer-station",
  "sm2:sands",
  "sm2:sands-props",
  "sm2:satcom-networks",
  "sm2:saturn-v",
  "sm2:schiffenberg-monastery",
  "sm2:scrabo-tower",
  "sm2:scrap-metal-transfer-station",
  "sm2:sentry-storage-inc",
  "sm2:serenity-subway-and-bus-station",
  "sm2:sg-simtropolis-station-dtr",
  "sm2:sg-simtropolis-station-str",
  "sm2:shocking-jimmys-electrical-supplies",
  "sm2:sim-gideon-ng-power-plant",
  "sm2:simcoe-correctional-facility",
  "sm2:small-oil-depots-a",
  "sm2:small-oil-depots-b",
  "sm2:small-oil-depots-c",
  "sm2:small-roundabout-bus-stop",
  "sm2:small-town-water-tower",
  "sm2:small-water-pump",
  "sm2:smallville-fedex-office",
  "sm2:sodium-hydroxide-storage-x1",
  "sm2:speedy-freight-inc",
  "sm2:stazione-di-santa-paola",
  "sm2:steampunk-bus-stops",
  "sm2:stones-vol1",
  "sm2:subway-stations-pack",
  "sm2:subzero-cooling-systems",
  "sm2:subzero-state-ltd",
  "sm2:suncor-solar-panels",
  "sm2:supertanker-corina",
  "sm2:tesla-dealership",
  "sm2:tesla-power-storage-pack",
  "sm2:tetradyne-data-center",
  "sm2:tetrapods-mmp",
  "sm2:the-lcbo-store",
  "sm2:the-pit",
  "sm2:the-thrift-store",
  "sm2:the-watchtower",
  "sm2:tire-shredding-co",
  "sm2:titanium-alloys-inc",
  "sm2:train-depot-east",
  "sm2:train-depot-north",
  "sm2:train-depot-south",
  "sm2:train-repair-yard",
  "sm2:trash-and-burn",
  "sm2:trash-barge-a",
  "sm2:trash-dumper",
  "sm2:true-rrw-dtr-sidings-vol1",
  "sm2:true-str-sidings-vol1",
  "sm2:tyrell-pharmaceutical-r-and-d",
  "sm2:u-store-it-self-storage",
  "sm2:underground-parking",
  "sm2:union-crane-and-shovel-co",
  "sm2:union-crane-and-shovel-company",
  "sm2:valensky-train-station",
  "sm2:valleymede-train-station",
  "sm2:verrano-post-office",
  "sm2:verrano-train-station",
  "sm2:very-large-oil-tank",
  "sm2:victoria-park-station",
  "sm2:victorian-train-station-north",
  "sm2:water-reservoir",
  "sm2:water-towers",
  "sm2:water-treatment-plant",
  "sm2:wilkinson-cotton-mill",
  "sm2:wind-power",
  "sm2:wind-power-inc",
  "sm2:yorkdale-glr-station",
  "sm2:yorkdale-subway-and-bus-hub"
]
```

</details>

### CODE REVIEW

**Comment by memo33** [comment]
Thanks a lot.

> * In order to add all this content, I had to add a few dependency packages that weren't available in the default channel too. If you want I can extract these into a separate PR so that the dependencies can be merged asap, while the review of Simmer2's actual content can take more time.

Yeah, I'd prefer moving them to a separate PR to make this one more manageable. You can squash the commits for simplicity. Reviewing 300 files at once is a bit much.

> * Some descriptions have been revamped a little manually (in order to pass the "no I or my" linting rule),

To explain this a little, my intention with that linting rule is to make it more inviting for anyone to edit the metadata, as the metadata is rarely written or updated by the original author of the STEX entry. It also avoids ambiguity as to who "I" refers to.

**Comment by sebamarynissen** [comment]
Fyi, I moved a bunch of the dependencies to #51. You can focus on that one first. Once merged into main, I can update this branch from main and then those files should be gone from this PR.

**Comment by sebamarynissen** [comment]
I updated the PR to reflect the changes from #51. *Only* 271 files left now.

**Comment by sebamarynissen** [comment]
@memo33 I've added the complete list of packages I've added as json format in the first commend as a collapsed section. That way you can easily copy-paste it in your sc4pac-plugins.json file to test them, rather than having to type it all in manually.

**Comment by sebamarynissen** [comment]
Closing in favor of https://github.com/sebamarynissen/simtropolis-channel/pull/48.

**Pull request closed without merging**
