### PR TITLE
add lbt dependencies

### PR DESCRIPTION
**Pull request by noah-severyn**

### CODE REVIEW

**Comment by memo33** [comment]
Thanks. I've set the installer type for the residentials models vol01 to "Clickteam". Otherwise, it would fail to extract.

For residentials models vol02, the files are contained in a Clickteam installer as well, which however is contained in a ZIP file within a ZIP file. In other words, there's an unnecessary layer of nested ZIPs and sc4pac doesn't do more than one layer of nesting, so the files fail to install. To resolve this, if possible the original upload could be project-ZIPped, as an installer for a single file is a bit pointless. Otherwise, I can comment out the package for the time being and merge this PR now.

**Comment by noah-severyn** [comment]
Thanks. The best course would be updating the STEX entry. Hold for a day or two - I'll do it this weekend and then come back to update this if necessary.

**Comment by noah-severyn** [comment]
I changed the STEX entries to remove the nested zips and just went ahead and removed the installers as well. Should be good to merge now.

**Comment by memo33** [comment]
Awesome. Thanks a lot.

**Pull request merged**
