### PR TITLE
add mattb325 civics

### PR DESCRIPTION
**Pull request by jflann**
All of matt's civics & rewards from Simtropolis plus some necessary dependencies.  Opening as a draft for now for discussion and review.

Most of these packages use the Simtropolis version although there are a few which use the mega pack on SC4E, which I only discovered existed when I was about 90% done with this project.

### CODE REVIEW

**Comment by memo33** [comment]
Wow, you are on fire. Thanks a lot.

I've installed the MaxisNite variants which went smoothly apart from an intermittent Cloudflare error.

The convention center seems to lack a model. Moreover there is a possibly unintentional growable lot named `IHT$$$3_6x6_Mattb325_Disease_Research_Center(IHT)_7dd39a56.SC4Lot`.

I've added `www.` to the SC4E URLs for consistency. This does not really matter as long as a given URL stays the same, but for caching purposes URLs with and without `www.` are treated differently, so I'd like to stick to one format.

**Comment by jflann** [comment]
> Wow, you are on fire. Thanks a lot.
> 
> I've installed the MaxisNite variants which went smoothly apart from an intermittent Cloudflare error.
> 
> The convention center seems to lack a model. Moreover there is a possibly unintentional growable lot named `IHT$$$3_6x6_Mattb325_Disease_Research_Center(IHT)_7dd39a56.SC4Lot`.
> 
> I've added `www.` to the SC4E URLs for consistency. This does not really matter as long as a given URL stays the same, but for caching purposes URLs with and without `www.` are treated differently, so I'd like to stick to one format.

I've corrected the issue with the missing model and also dealt with the errant growable lot.

**Comment by memo33** [comment]
> I've corrected the issue with the missing model and also dealt with the errant growable lot.

Thanks.

Regarding the use of SC4E or ST assets, this should not matter too much, as usually the files you end up with should be the same, at least functionally. There are pros for each.

Two more questions though:

What is your opinion on adding more subfolders within the plugins folder? (This can always be dealt with later though.)

Should all of these new packages be added to the [Highlights](https://memo33.github.io/sc4pac/#/packages) page or just a selection of them? Currently, that page is the best place to find stuff to install, I feel, as there isn't any categorization scheme yet.

**Comment by jflann** [comment]
> What is your opinion on adding more subfolders within the plugins folder? (This can always be dealt with later though.)

I think broad categories like civics could benefit from additional subfolders.  To me it makes a lot of sense to split them into smaller categories by their function (health, safety, education, government, etc).  Others are more difficult to subdivide further in a way that makes sense to everyone.  For example, there are a number of ways you could classify residential (tileset, wealth, density) and so it would require some thought.  However, for those folders in which folks might install quite a few packages, it could become a bit cumbersome to leave things relatively flat.  I think we probably should come up with a system, we just need to take care to design something relatively simple that can be applied to all or nearly all packages you'd find within that class.

> Should all of these new packages be added to the [Highlights](https://memo33.github.io/sc4pac/#/packages) page or just a selection of them? Currently, that page is the best place to find stuff to install, I feel, as there isn't any categorization scheme yet.

Probably not every package, but perhaps a few from each subcategory.  E.g.

**Civics - Education**

- mattb325:urban-school
- mattb325:city-college
- mattb325:diagonal-library

**Civics - Goverment**

- mattb325:sioux-falls-city-hall
- mattb325:modern-bureau-of-bureaucracy
- mattb325:meeting-hall

**Civics - Health**

- mattb325:large-modern-hospital
- mattb325:clinic

**Civics - Safety**

- mattb325:modern-police-station
- mattb325:modern-fire-station
- mattb325:old-nypd-headquarters

**Civics - Religion**

- mattb325:new-england-style-church
- mattb325:st-johns-church

**Civics - Miscellaneous**

- mattb325:galaxy-casino-hotel
- mattb325:griffith-observatory
- mattb325:london-stock-exchange
- mattb325:convention-center
- mattb325:research-center

**Comment by memo33** [comment]
How about
```
610-safety
620-education
630-health
640-government
650-religion
660-parks
```
with miscellaneous stuff going in `600-civics`? Alternatively, we could create nested subfolders in `600-civics`, but I think consistently keeping the `*.sc4pac` folders at the same depth level and not mixing them with regular subfolders has some value. I'm going to make the changes later and merge the PR.

**Comment by jflann** [comment]
Seems like a good solution to me, thank you for taking care of that.  Also, my apologies for making quite a few silly mistakes, I'm glad you caught them.

**Comment by memo33** [comment]
No worries. I've added a few more checks to the CI to help us catch them more easily in the future.

**Pull request merged**
